//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTibiaX.IPChanger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppLocal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLocal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KTibiaX.IPChanger.AppLocal", typeof(AppLocal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking updates....
        /// </summary>
        internal static string strCheckingUpdate {
            get {
                return ResourceManager.GetString("strCheckingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia Client not found!.
        /// </summary>
        internal static string strClientNotFound {
            get {
                return ResourceManager.GetString("strClientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom config file not found!\nRecord removed..
        /// </summary>
        internal static string strConfigFileNotFound {
            get {
                return ResourceManager.GetString("strConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file not found!.
        /// </summary>
        internal static string strConfigFileNotFoundfrm {
            get {
                return ResourceManager.GetString("strConfigFileNotFoundfrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Default].
        /// </summary>
        internal static string strDefault {
            get {
                return ResourceManager.GetString("strDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current server.\nAre you shure?.
        /// </summary>
        internal static string strDeleteServer {
            get {
                return ResourceManager.GetString("strDeleteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server address!.
        /// </summary>
        internal static string strInvalidAddress {
            get {
                return ResourceManager.GetString("strInvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Description!.
        /// </summary>
        internal static string strInvalidDescription {
            get {
                return ResourceManager.GetString("strInvalidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tibia Version!.
        /// </summary>
        internal static string strInvalidVersion {
            get {
                return ResourceManager.GetString("strInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP Already Exist!.
        /// </summary>
        internal static string strIPExist {
            get {
                return ResourceManager.GetString("strIPExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        internal static string strLagChecking {
            get {
                return ResourceManager.GetString("strLagChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your desired language:.
        /// </summary>
        internal static string strLanguage {
            get {
                return ResourceManager.GetString("strLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT Server Maps Directory not found!\nPath restored to:.
        /// </summary>
        internal static string strMapError {
            get {
                return ResourceManager.GetString("strMapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart the application to the changes take effect..
        /// </summary>
        internal static string strMustRestart {
            get {
                return ResourceManager.GetString("strMustRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version: .
        /// </summary>
        internal static string strNewVersion {
            get {
                return ResourceManager.GetString("strNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Checked!.
        /// </summary>
        internal static string strNotChecked {
            get {
                return ResourceManager.GetString("strNotChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates needed!.
        /// </summary>
        internal static string strNoUpdates {
            get {
                return ResourceManager.GetString("strNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Off Line!.
        /// </summary>
        internal static string strOffLine {
            get {
                return ResourceManager.GetString("strOffLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Online!.
        /// </summary>
        internal static string strOnline {
            get {
                return ResourceManager.GetString("strOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date: .
        /// </summary>
        internal static string strReleaseDate {
            get {
                return ResourceManager.GetString("strReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string strSelect {
            get {
                return ResourceManager.GetString("strSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select or type a server].
        /// </summary>
        internal static string strSelectServer {
            get {
                return ResourceManager.GetString("strSelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you Shure?.
        /// </summary>
        internal static string strShure {
            get {
                return ResourceManager.GetString("strShure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start Tibia.exe.
        /// </summary>
        internal static string strStartFail {
            get {
                return ResourceManager.GetString("strStartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavaliable.
        /// </summary>
        internal static string strUnavaliable {
            get {
                return ResourceManager.GetString("strUnavaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check updates..
        /// </summary>
        internal static string strUpdateError {
            get {
                return ResourceManager.GetString("strUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        internal static string strUpdateFound {
            get {
                return ResourceManager.GetString("strUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://tibialaunch.googlecode.com/svn/trunk/Version/version.en-us.xml.
        /// </summary>
        internal static string strUpdateURL {
            get {
                return ResourceManager.GetString("strUpdateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://tibialaunch.googlecode.com.
        /// </summary>
        internal static string strUrl {
            get {
                return ResourceManager.GetString("strUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Version: .
        /// </summary>
        internal static string strVersion {
            get {
                return ResourceManager.GetString("strVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server version is different of Config File Version!.
        /// </summary>
        internal static string strVersionConflict {
            get {
                return ResourceManager.GetString("strVersionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Tibia Version is not Supported!.
        /// </summary>
        internal static string strVersionNotSupported {
            get {
                return ResourceManager.GetString("strVersionNotSupported", resourceCulture);
            }
        }
    }
}
